---
- hosts: localhost
  vars:
    db_password: password
  tasks:
    - name: Copy MariaDB.repo 
      become: yes
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644

    - name: Turn on MariaDB service
      become: yes
      service: name=mariadb state=started enabled=yes
      
    - name: Unpack db.tgz
      unarchive: src=db/db.tgz dest=~/ mode=0755
      #Copying db.tgz and creating a directory 

    - name: Show errors
      command: ./make_databases.sh {{ db_password }} localhost chdir=~/db
      ignore_errors: True
