---
- hosts: db
  vars:
    db_password: password
  tasks:
    - name: Copy MariaDB.repo 
      become: yes
      copy: src=db/MariaDB.repo dest=/etc/yum.repos.d/MariaDB.repo mode=0644

    - name: Install MariaDB-client
      become: yes
      yum: name=MariaDB-client update_cache=yes state=present

    - name: Turn on MariaDB service
      become: yes
      service: name=mariadb state=started enabled=yes
      
    - name: Copying db.tgz and creating a directory 
      unarchive: src=db/db.tgz dest=~/ mode=0755

    - name: Make database for RDS
      command: ./make_databases.sh {{ db_password }} mariadb.ckb2fibwtqu4.us-west-2.rds.amazonaws.com
      ignore_errors: True
